### ISSUE TITLE
Anjuke unicorn trouble

### ISSUE THREAD

**Issue by spx123** [iisquare/snippet#1]
Hi, could you please tell me, how to pass multiple parameters of Java_Sign_getSign0 to unicorn engine? I can't seem to find it

**Comment by spx123** [comment]
`JNIEXPORT jstring JNICALL Java_Sign_getSign0
  (JNIEnv *env, jclass, jstring, jstring, jobject, jstring, jint)
{
    uc_engine *uc;
    uc_err err;
    uc_hook trace1, trace2;
    uint32_t sp = STACK_ADDR;
    offset = 0;
    err = uc_open(UC_ARCH_ARM, UC_MODE_THUMB, &uc);
    if (err) {
        char *message;
        sprintf(message, "Failed on uc_open() with error returned: %u (%s)\n",
            err, uc_strerror(err));
        return env->NewStringUTF(message);
    }
    char plain[] = "/vps?tvid=11949478009&vid=7b23569cbed511dd58bcd6ce9ddd7b42&v=0&qypid=11949478009_unknown&src=02022001010000000000&tm=1519712402&k_tag=1&k_uid=359125052784388&bid=1&pt=0&d=1&s=0&rs=1&dfp=1413357b5efa4a4130b327995c377ebb38fbd916698ed95a28f56939e9d8825592&k_ver=9.0.0&k_ft1=859834543&k_err_retries=0&qd_v=1";
    uc_mem_map(uc, PARAM_ADDR, PARAM_SIZE, UC_PROT_ALL);
    uc_mem_map(uc, BASE, CODE_SIZE, UC_PROT_ALL);
    uint32_t r0 = PARAM_ADDR;
    uint32_t sp_start = sp + STACK_SIZE;
    int ret=uc_mem_map(uc, sp, sp_start - sp, UC_PROT_ALL);
    uint32_t len = 0;
    unsigned char* code = read_file("../files/libsignutil.so", &len);
    uc_mem_write(uc, BASE, code, len);
    free(code);
    create_mem(uc, plain, strlen(plain) + 1);
    uc_reg_write(uc, UC_ARM_REG_R0, &r0);
    uc_reg_write(uc, UC_ARM_REG_SP, &sp);
    err = uc_emu_start(uc, BASE + 0x1BAC + 1, BASE + 0x1BAC + 0x31C, 0, 0);
    if (err) {
        char *message;
        sprintf(message, "Failed on uc_emu_start() with error returned: %u\n", err);
        uc_close(uc);
        return env->NewStringUTF(message);
    }
    char buffer[4096] = "";
    uc_reg_read(uc, UC_ARM_REG_R0, &r0);
    uc_mem_read(uc, r0, buffer, 4096);
    uc_close(uc);
    return env->NewStringUTF(buffer);
}`

**Comment by iisquare** [comment]
paste your test case, please

**Comment by iisquare** [comment]
the code has been removed, thanks for your support.
